In [28]:
import pandas as pd
import numpy as np

df = pd.read_csv("CustomerServiceDataSet.csv")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 559 entries, 0 to 558
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Branch                 559 non-null    object
 1   Call Purpose           559 non-null    object
 2   Time Block             559 non-null    object
 3   Incoming or Outgoing   559 non-null    object
 4   Queue                  559 non-null    object
 5   Rep ID                 559 non-null    object
 6   Sale                   559 non-null    object
 7   Lost Call              559 non-null    int64
 8   Abandoned              559 non-null    int64
 9   Busy Minutes           559 non-null    int64
 10  Not Ready Minutes      559 non-null    int64
 11  Incoming Wait Time     208 non-null    float64
 12  During Call Wait Time  559 non-null    int64
 13  Calls                  559 non-null    int64
dtypes: float64(1), int64(6), object(7)
memory usage: 61.3+ KB
None

In [29]:
# EDA

print(df.describe())

        Lost Call   Abandoned  Busy Minutes  Not Ready Minutes  \
count  559.000000  559.000000    559.000000         559.000000
mean     0.028623    0.019678     10.025045           1.912343
std      0.166893    0.139016      1.405091           0.821644
min      0.000000    0.000000      8.000000           1.000000
25%      0.000000    0.000000      9.000000           1.000000
50%      0.000000    0.000000     10.000000           2.000000
75%      0.000000    0.000000     11.000000           3.000000
max      1.000000    1.000000     12.000000           3.000000

       Incoming Wait Time  During Call Wait Time  Calls
count          208.000000             559.000000  559.0
mean             3.019231               3.028623    1.0
std              1.365417               0.831225    0.0
min              1.000000               2.000000    1.0
25%              2.000000               2.000000    1.0
50%              3.000000               3.000000    1.0
75%              4.000000               4.000000    1.0
max              5.000000               4.000000    1.0

In [30]:
print(df.head(25))

   Branch     Call Purpose Time Block Incoming or Outgoing Queue  Rep ID Sale  \
0   North        Complaint    9:00 AM             Incoming     B   Brent   NO
1   South    Sales Support   10:00 AM             Incoming     D    Kate   NO
2   South    Sales Support   10:00 AM             Incoming     C    Eric   NO
3   South    Sales Support   10:00 AM             Incoming     C   Susan   NO
4   South    Sales Support   10:00 AM             Incoming     C   Alice   NO
5   North    Sales Support   11:00 AM             Incoming     A     Cam   NO
6   North    Sales Support   11:00 AM             Incoming     B    Todd   NO
7   South    Sales Support   12:00 PM             Incoming     C   Sandy   NO
8   South    Sales Support    1:00 PM             Incoming     D    Karl   NO
9   North    Sales Support    4:00 PM             Incoming     B   Brent   NO
10  South  Product Support   11:00 AM             Incoming     C   Sandy   NO
11  South  Product Support   12:00 PM             Incoming     C   Sandy   NO
12  North  Product Support   12:00 PM             Incoming     B   Brent   NO
13  North  Product Support    2:00 PM             Incoming     B    Duke   NO
14  South  Product Support    2:00 PM             Incoming     D   Randy   NO
15  North  Product Support    2:00 PM             Incoming     A     Joe   NO
16  North  Product Support    2:00 PM             Incoming     B   Lilly   NO
17  South  Product Support    3:00 PM             Incoming     D  George   NO
18  South  Product Support    3:00 PM             Incoming     D   Helga   NO
19  North  Product Support    3:00 PM             Incoming     B    Duke   NO
20  North  Product Support    3:00 PM             Incoming     A     Cam   NO
21  North  Product Support    4:00 PM             Incoming     A     Joe   NO
22  South  Product Support    4:00 PM             Incoming     D    Josh   NO
23  North  Product Support    4:00 PM             Incoming     A  Amanda   NO
24  South  Product Support    4:00 PM             Incoming     D  George   NO

    Lost Call  Abandoned  Busy Minutes  Not Ready Minutes  Incoming Wait Time  \
0           0          1             9                  2                 1.0
1           0          0             9                  1                 1.0
2           0          0             8                  2                 1.0
3           0          0            10                  2                 1.0
4           0          0            12                  1                 1.0
5           0          0            11                  1                 1.0
6           0          0             9                  3                 1.0
7           0          0             8                  3                 1.0
8           0          0             9                  1                 1.0
9           0          0            11                  2                 1.0
10          0          0             8                  1                 1.0
11          0          0             8                  1                 1.0
12          0          0             8                  2                 1.0
13          0          0            12                  2                 1.0
14          0          0            11                  2                 1.0
15          0          0             8                  1                 1.0
16          0          0            11                  2                 1.0
17          0          0             8                  3                 1.0
18          0          0             9                  1                 1.0
19          0          0            12                  2                 1.0
20          0          0            11                  3                 1.0
21          0          0            11                  3                 1.0
22          0          0            11                  3                 1.0
23          0          0            10                  3                 1.0
24          0          0            10                  1                 1.0

    During Call Wait Time  Calls
0                       4      1
1                       2      1
2                       4      1
3                       4      1
4                       3      1
5                       3      1
6                       3      1
7                       3      1
8                       4      1
9                       4      1
10                      2      1
11                      3      1
12                      4      1
13                      2      1
14                      4      1
15                      3      1
16                      3      1
17                      4      1
18                      3      1
19                      4      1
20                      4      1
21                      4      1
22                      3      1
23                      2      1
24                      4      1

In [31]:
print(df["Lost Call"].value_counts())

0    543
1     16
Name: Lost Call, dtype: int64

In [32]:
print(df["Abandoned"].value_counts())

0    548
1     11
Name: Abandoned, dtype: int64

In [33]:
print(df["Rep ID"].value_counts())

Brent     37
Eric      35
Randy     33
Sandy     32
Helga     31
Lilly     30
Kate      29
Duke      29
Todd      29
George    29
Karl      28
Joe       26
Susan     26
Josh      26
Sharon    25
Cam       24
Xander    24
Amanda    23
Andy      23
Alice     20
Name: Rep ID, dtype: int64

In [34]:
queue_df = df.groupby("Queue")
print(queue_df.describe())

      Lost Call                                              Abandoned  \
          count      mean       std  min  25%  50%  75%  max     count
Queue
A          96.0  0.010417  0.102062  0.0  0.0  0.0  0.0  1.0      96.0
B         149.0  0.026846  0.162177  0.0  0.0  0.0  0.0  1.0     149.0
C         138.0  0.028986  0.168377  0.0  0.0  0.0  0.0  1.0     138.0
D         176.0  0.039773  0.195982  0.0  0.0  0.0  0.0  1.0     176.0

                 ... During Call Wait Time       Calls                      \
           mean  ...                   75%  max  count mean  std  min  25%
Queue            ...
A      0.041667  ...                  3.25  4.0   96.0  1.0  0.0  1.0  1.0
B      0.020134  ...                  4.00  4.0  149.0  1.0  0.0  1.0  1.0
C      0.007246  ...                  4.00  4.0  138.0  1.0  0.0  1.0  1.0
D      0.017045  ...                  4.00  4.0  176.0  1.0  0.0  1.0  1.0


       50%  75%  max
Queue
A      1.0  1.0  1.0
B      1.0  1.0  1.0
C      1.0  1.0  1.0
D      1.0  1.0  1.0

[4 rows x 56 columns]

In [35]:
print(df["Sale"].value_counts())

NO      542
YES      16
YES       1
Name: Sale, dtype: int64

In [36]:
print(df["Time Block"].value_counts())

12:00 PM    120
10:00 AM     99
3:00 PM      73
2:00 PM      65
11:00 AM     56
4:00 PM      53
5:00 PM      43
1:00 PM      40
9:00 AM      10
Name: Time Block, dtype: int64

In [37]:
print(df["Incoming or Outgoing"].value_counts())

Outgoing    351
Incoming    208
Name: Incoming or Outgoing, dtype: int64

In [38]:
print(df.groupby("Incoming or Outgoing").head(25))

    Branch     Call Purpose Time Block Incoming or Outgoing Queue  Rep ID  \
0    North        Complaint    9:00 AM             Incoming     B   Brent
1    South    Sales Support   10:00 AM             Incoming     D    Kate
2    South    Sales Support   10:00 AM             Incoming     C    Eric
3    South    Sales Support   10:00 AM             Incoming     C   Susan
4    South    Sales Support   10:00 AM             Incoming     C   Alice
5    North    Sales Support   11:00 AM             Incoming     A     Cam
6    North    Sales Support   11:00 AM             Incoming     B    Todd
7    South    Sales Support   12:00 PM             Incoming     C   Sandy
8    South    Sales Support    1:00 PM             Incoming     D    Karl
9    North    Sales Support    4:00 PM             Incoming     B   Brent
10   South  Product Support   11:00 AM             Incoming     C   Sandy
11   South  Product Support   12:00 PM             Incoming     C   Sandy
12   North  Product Support   12:00 PM             Incoming     B   Brent
13   North  Product Support    2:00 PM             Incoming     B    Duke
14   South  Product Support    2:00 PM             Incoming     D   Randy
15   North  Product Support    2:00 PM             Incoming     A     Joe
16   North  Product Support    2:00 PM             Incoming     B   Lilly
17   South  Product Support    3:00 PM             Incoming     D  George
18   South  Product Support    3:00 PM             Incoming     D   Helga
19   North  Product Support    3:00 PM             Incoming     B    Duke
20   North  Product Support    3:00 PM             Incoming     A     Cam
21   North  Product Support    4:00 PM             Incoming     A     Joe
22   South  Product Support    4:00 PM             Incoming     D    Josh
23   North  Product Support    4:00 PM             Incoming     A  Amanda
24   South  Product Support    4:00 PM             Incoming     D  George
208  South  Product Support    9:00 AM             Outgoing     C   Sandy
209  South  Product Support    9:00 AM             Outgoing     C   Susan
210  South  Product Support    9:00 AM             Outgoing     D    Karl
211  South    Sales Support   10:00 AM             Outgoing     C   Susan
212  North    Sales Support   10:00 AM             Outgoing     A     Cam
213  North    Sales Support   10:00 AM             Outgoing     B    Duke
214  North    Sales Support   11:00 AM             Outgoing     B  Xander
215  South    Sales Support   11:00 AM             Outgoing     D    Josh
216  South    Sales Support   12:00 PM             Outgoing     D    Josh
217  South    Sales Support   12:00 PM             Outgoing     C  Sharon
218  North  Product Support    9:00 AM             Outgoing     B    Duke
219  South  Product Support    1:00 PM             Outgoing     D   Randy
220  South  Product Support    5:00 PM             Outgoing     D    Josh
221  South  Product Support    5:00 PM             Outgoing     D   Randy
222  North    Sales Support   10:00 AM             Outgoing     B   Lilly
223  North    Sales Support   10:00 AM             Outgoing     B   Lilly
224  South    Sales Support   10:00 AM             Outgoing     D   Helga
225  South    Sales Support   10:00 AM             Outgoing     C  Sharon
226  North  Product Support    9:00 AM             Outgoing     A    Andy
227  North  Product Support   11:00 AM             Outgoing     A  Amanda
228  South  Product Support    3:00 PM             Outgoing     D   Helga
229  North    Sales Support   10:00 AM             Outgoing     B   Brent
230  South    Sales Support   10:00 AM             Outgoing     D  George
231  South    Sales Support   10:00 AM             Outgoing     D    Karl
232  North    Sales Support   10:00 AM             Outgoing     B    Todd

    Sale  Lost Call  Abandoned  Busy Minutes  Not Ready Minutes  \
0     NO          0          1             9                  2
1     NO          0          0             9                  1
2     NO          0          0             8                  2
3     NO          0          0            10                  2
4     NO          0          0            12                  1
5     NO          0          0            11                  1
6     NO          0          0             9                  3
7     NO          0          0             8                  3
8     NO          0          0             9                  1
9     NO          0          0            11                  2
10    NO          0          0             8                  1
11    NO          0          0             8                  1
12    NO          0          0             8                  2
13    NO          0          0            12                  2
14    NO          0          0            11                  2
15    NO          0          0             8                  1
16    NO          0          0            11                  2
17    NO          0          0             8                  3
18    NO          0          0             9                  1
19    NO          0          0            12                  2
20    NO          0          0            11                  3
21    NO          0          0            11                  3
22    NO          0          0            11                  3
23    NO          0          0            10                  3
24    NO          0          0            10                  1
208   NO          1          0            12                  2
209   NO          1          0             9                  3
210   NO          1          0             9                  3
211   NO          1          0             8                  2
212   NO          1          0             8                  1
213   NO          1          0            10                  2
214   NO          1          0            10                  1
215   NO          1          0             9                  2
216   NO          1          0            12                  1
217   NO          1          0            11                  2
218   NO          1          0            12                  1
219   NO          1          0             9                  1
220   NO          1          0             9                  1
221   NO          1          0             9                  3
222  YES          0          1             9                  3
223  YES          0          1            12                  1
224   NO          0          1             9                  1
225   NO          0          1             9                  1
226   NO          0          1            12                  2
227   NO          0          1            11                  2
228   NO          0          1            12                  1
229   NO          0          0            11                  3
230   NO          0          0             8                  3
231   NO          0          0            11                  2
232   NO          0          0            10                  2

     Incoming Wait Time  During Call Wait Time  Calls
0                   1.0                      4      1
1                   1.0                      2      1
2                   1.0                      4      1
3                   1.0                      4      1
4                   1.0                      3      1
5                   1.0                      3      1
6                   1.0                      3      1
7                   1.0                      3      1
8                   1.0                      4      1
9                   1.0                      4      1
10                  1.0                      2      1
11                  1.0                      3      1
12                  1.0                      4      1
13                  1.0                      2      1
14                  1.0                      4      1
15                  1.0                      3      1
16                  1.0                      3      1
17                  1.0                      4      1
18                  1.0                      3      1
19                  1.0                      4      1
20                  1.0                      4      1
21                  1.0                      4      1
22                  1.0                      3      1
23                  1.0                      2      1
24                  1.0                      4      1
208                 NaN                      4      1
209                 NaN                      4      1
210                 NaN                      4      1
211                 NaN                      4      1
212                 NaN                      2      1
213                 NaN                      4      1
214                 NaN                      4      1
215                 NaN                      4      1
216                 NaN                      3      1
217                 NaN                      4      1
218                 NaN                      2      1
219                 NaN                      3      1
220                 NaN                      4      1
221                 NaN                      2      1
222                 NaN                      4      1
223                 NaN                      4      1
224                 NaN                      4      1
225                 NaN                      3      1
226                 NaN                      2      1
227                 NaN                      2      1
228                 NaN                      2      1
229                 NaN                      4      1
230                 NaN                      2      1
231                 NaN                      2      1
232                 NaN                      2      1

In [39]:
print(df["Incoming Wait Time"].value_counts())

4.0    50
2.0    44
3.0    41
1.0    37
5.0    36
Name: Incoming Wait Time, dtype: int64

In [40]:
rep_df = df.groupby("Rep ID").sum()
rep_df

# We should have them plot something related to this!

,Lost Call,Abandoned,Busy Minutes,Not Ready Minutes,Incoming Wait Time,During Call Wait Time,Calls
Rep ID,,,,,,,
Alice,0,0,199,46,15.0,58,20
Amanda,0,1,229,43,12.0,60,23
Andy,0,3,228,43,36.0,65,23
Brent,0,1,362,71,17.0,117,37
Cam,1,0,233,46,32.0,66,24
Duke,2,0,292,56,39.0,85,29
Eric,0,0,361,54,47.0,112,35
George,0,0,298,53,41.0,87,29
Helga,0,2,292,58,36.0,95,31
Joe,0,0,256,49,36.0,81,26
Josh,3,0,260,50,31.0,83,26
Karl,1,0,287,61,26.0,85,28
Kate,0,0,291,61,37.0,83,29
Lilly,0,2,307,59,37.0,88,30
Randy,3,1,320,66,47.0,98,33
Sandy,1,0,325,60,34.0,100,32
Sharon,1,1,257,38,29.0,77,25
Susan,2,0,267,53,35.0,88,26
Todd,1,0,296,58,21.0,97,29
Xander,1,0,244,44,20.0,68,24

In [41]:
d = dict(tuple(df.groupby("Branch")))
south_df = pd.DataFrame(d["South"])
print(south_df.info())

south_df.to_csv("SouthCallCenter.csv")

<class 'pandas.core.frame.DataFrame'>
Int64Index: 314 entries, 1 to 556
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Branch                 314 non-null    object
 1   Call Purpose           314 non-null    object
 2   Time Block             314 non-null    object
 3   Incoming or Outgoing   314 non-null    object
 4   Queue                  314 non-null    object
 5   Rep ID                 314 non-null    object
 6   Sale                   314 non-null    object
 7   Lost Call              314 non-null    int64
 8   Abandoned              314 non-null    int64
 9   Busy Minutes           314 non-null    int64
 10  Not Ready Minutes      314 non-null    int64
 11  Incoming Wait Time     126 non-null    float64
 12  During Call Wait Time  314 non-null    int64
 13  Calls                  314 non-null    int64
dtypes: float64(1), int64(6), object(7)
memory usage: 36.8+ KB
None

In [42]:
north_df = pd.DataFrame(d["North"])
print(north_df.info())

north_df.to_csv("NorthCallCenter.csv")

<class 'pandas.core.frame.DataFrame'>
Int64Index: 245 entries, 0 to 558
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Branch                 245 non-null    object
 1   Call Purpose           245 non-null    object
 2   Time Block             245 non-null    object
 3   Incoming or Outgoing   245 non-null    object
 4   Queue                  245 non-null    object
 5   Rep ID                 245 non-null    object
 6   Sale                   245 non-null    object
 7   Lost Call              245 non-null    int64
 8   Abandoned              245 non-null    int64
 9   Busy Minutes           245 non-null    int64
 10  Not Ready Minutes      245 non-null    int64
 11  Incoming Wait Time     82 non-null     float64
 12  During Call Wait Time  245 non-null    int64
 13  Calls                  245 non-null    int64
dtypes: float64(1), int64(6), object(7)
memory usage: 28.7+ KB
None